name: Use Packer to generate a Cortex XDR-enabled AMI.

on:
  workflow_dispatch:
    inputs:
      AWS_REGION:
        description: 'AWS region in which to deploy the infrastructure'
        required: true
        default: 'eu-west-3'
      XDR_API_URL:
        description: 'API URL of the Cortex Tenant'
        required: true
        default: 'https://api-emea-cxsiamp.xdr.eu.paloaltonetworks.com'
      DISTRIBUTION_ID:
        description: 'Distribution_ID = ID of XDR Installer on Cortex Cloud'
        required: true
        default: '1b806ed9213f480c9041e1c310d18bc8'
      XDR_TAGS:
        description: 'Tags to add to the Agent in the VM Image (comma-separated)'
        required: true
        default: 'CORTEX,AMI,CLEY'

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.AWS_REGION }}

      - name: Set up Packer
        uses: hashicorp-contrib/setup-packer@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run Packer Init
        run: packer init .
        working-directory: ./packer-templates

      - name: Validate Packer template
        run: packer validate AMI-XDR-template.pkr.hcl
        working-directory: ./packer-templates
        env:
          PKR_VAR_aws_region: ${{ github.event.inputs.AWS_REGION }}
          PKR_VAR_xdr_url: ${{ github.event.inputs.XDR_API_URL }}
          PKR_VAR_distribution_id: ${{ github.event.inputs.DISTRIBUTION_ID }}
          PKR_VAR_auth_id: ${{ secrets.CORTEX_AUTH_ID }}
          PKR_VAR_auth_token: ${{ secrets.CORTEX_AUTH_TOKEN }}
          PKR_VAR_xdr_tags: ${{ github.event.inputs.XDR_TAGS }}

      - name: Build AMI with Packer
        run: packer build AMI-XDR-template.pkr.hcl
        working-directory: ./packer-templates
        env:
          PKR_VAR_aws_region: ${{ github.event.inputs.AWS_REGION }}
          PKR_VAR_xdr_url: ${{ github.event.inputs.XDR_API_URL }}
          PKR_VAR_distribution_id: ${{ github.event.inputs.DISTRIBUTION_ID }}
          PKR_VAR_auth_id: ${{ secrets.CORTEX_AUTH_ID }}
          PKR_VAR_auth_token: ${{ secrets.CORTEX_AUTH_TOKEN }}
          PKR_VAR_xdr_tags: ${{ github.event.inputs.XDR_TAGS }}
